### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by oatsoda** [oatsoda/BuildMonitor#25]
> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.InvalidOperationException: Sequence contains no elements
>    at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
>    at BuildMonitor.UI.Controls.BuildDefinitionsListForm.RemoveUnusedControls(Int32 numberToRemove)
>    at BuildMonitor.UI.Controls.BuildDefinitionsListForm.UpdateBuildControls(IEnumerable`1 buildDetails)
>    at BuildMonitor.UI.Controls.BuildDefinitionsListForm.<>c__DisplayClass22_0.<OnBuildMonitorOnUpdated>b__0()
>    at BuildMonitor.UI.Helpers.ControlExtensions.<>c__DisplayClass1_0.<InvokeIfRequired>b__0()
>    at System.Windows.Forms.Control.InvokeMarshaledCallbackDo(ThreadMethodEntry tme)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
>    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
>    at System.Windows.Forms.Control.InvokeMarshaledCallbacks()
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
> ----------------------------------------
> BuildMonitor.App
>     Assembly Version: 1.5.3.0
>     Win32 Version: 1.5.3.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/Build%20Monitor/BuildMonitor.App.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3314.0 built by: NET472REL1LAST_B
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> BuildMonitor.UI
>     Assembly Version: 1.5.3.0
>     Win32 Version: 1.5.3.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/Build%20Monitor/BuildMonitor.UI.DLL
> ----------------------------------------
> BuildMonitor.TfsOnline
>     Assembly Version: 1.5.3.0
>     Win32 Version: 1.5.3.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/Build%20Monitor/BuildMonitor.TfsOnline.DLL
> ----------------------------------------
> BuildMonitor.Core
>     Assembly Version: 1.5.3.0
>     Win32 Version: 1.5.3.0
>     CodeBase: file:///C:/Program%20Files%20(x86)/Build%20Monitor/BuildMonitor.Core.DLL
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> Accessibility
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> ----------------------------------------
> System.Net.Http
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll
> ----------------------------------------
> System.Security
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3101.0 built by: NET472REL1LAST_B
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Security/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Security.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3324.0 built by: NET472REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> Newtonsoft.Json
>     Assembly Version: 9.0.0.0
>     Win32 Version: 9.0.1.19813
>     CodeBase: file:///C:/Program%20Files%20(x86)/Build%20Monitor/Newtonsoft.Json.DLL
> ----------------------------------------
> System.Numerics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.7.3056.0 built by: NET472REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

**Comment by oatsoda** [comment]
Closing until it occurs again
